### PR TITLE
Dynamic node remote

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
Improved importing mechanics on server-side node. 

The method here mimics what webpack does for you. 

1) We attach the remoteEntry as an external (non_webpack_require) 
2) We use the required container and initialize it with share scopes
3) We get remote Modules from the federated runtime.

`remotes` in webpack tells the parser what to do when it processes the file. Instead of having webpack resolve it, we resolve it to a RemoteModule that's generated. Those remote modules contain the get and init function calls which auto connects to the remote webpack runtime. 

so `require("next1/nav")`, the parser sees the `request.startsWith('next1/')` webpack sees the request as `[scope]/[request]` so it splits the global off the name and looks for a module that matches `./[request]`
and that's how webpack knows what you're looking for or how to find it. If webpack doesn't know about remotes, it will attempt to resolve them to files. Since this is all at-runtime, we simply do what webpack does, manually.

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
This implementation is better than the one in my repositories. I likely will adopt this / similar implementation myself. 

At least until Next makes the adjustments required to their platform

**Comment by Kinbaum** [comment]
@ScriptedAlchemy Now that we've marked React as being external, there are a ton of warnings being thrown to the terminal. In addition to that, I've noticed things like `useRouter` returning `null` rather than the `ServerRouter` object.

**Comment by Kinbaum** [comment]
> This implementation is better than the one in my repositories. I likely will adopt this / similar implementation myself.
> 
> At least until Next makes the adjustments required to their platform

The only other thing I'd like to see / know how to do the right way is grab the remote entry when it's not on disk. So instead of walking the file system, require the remote via URL using the low-level APIs server side.

**Comment by ScriptedAlchemy** [comment]
Thats not how webpack works in node builds, however we have created a custom webpack target for streaming code in over the network. https://github.com/jacob-ebey/vercel-federated-gql-module-a

**Pull request closed without merging**
